<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2015-07-17 07:24

$extensionPath = t3lib_extMgm::extPath('t3jquery');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_t3jquery' => $extensionPath . 'Migrations/Code/LegacyClassesForIde.php',
	'tx_t3jquery_module1' => $extensionClassesPath . 'Module/index.php',
	'tx_t3jquery_tsparserext' => $extensionPath . 'Migrations/Code/LegacyClassesForIde.php',
	'tx_t3jquery_viewhelpers_addjqueryandscriptviewhelper' => $extensionPath . 'Migrations/Code/LegacyClassesForIde.php',
	'tx_t3jquery_viewhelpers_addjqueryviewhelper' => $extensionPath . 'Migrations/Code/LegacyClassesForIde.php',
	'analyzeJqJS' => $extensionPath . 'Classes/Module/class.analyzeJqJS.php',
	'JavaScriptPacker' => $extensionPath . 'Classes/Module/class.JavaScriptPacker.php'
);
?>